### ISSUE TITLE
[Compatibility] Fake Name

### ISSUE THREAD

**Issue by Sablam** [kreezxil/Localized-Chat#2]
Hi there,

Thank for the mod.
Could it be possible to have a version that doesn't override chat format so it could be compatible with https://minecraft.curseforge.com/projects/fakename

Sincerely,

**Comment by kreezxil** [comment]
released 3.0.0

these are the changes:
stripped it down to the core parts.
Made sure it handles ranges correctly.
cleaned up the config.
like an American Idol song I fully made this my own mod this time.
Added alternative prefixing to be used in place of displaying numbers.
added compatibility with fakeName mod.
added compatibility with any mod that modifies the name of the player using the customNameTag NBT compound.
