### ISSUE TITLE
Allow the mod to work on operators

### ISSUE THREAD

**Issue by Kevino36** [kreezxil/Localized-Chat#3]
Currently, operators override Localized Chat and are able to communicate from across the server. A config option to make the mod apply to operators would be very useful.

**Comment by kreezxil** [comment]
released 3.0.0

these are changes:

stripped it down to the core parts.
Made sure it handles ranges correctly.
cleaned up the config.
like an American Idol song I fully made this my own mod this time.
Added alternative prefixing to be used in place of displaying numbers.
added compatibility with fakeName mod.
added compatibility with any mod that modifies the name of the player using the customNameTag NBT compound.
