### ISSUE TITLE
[Problems/Ideas] - To make the group chat more realistic/flexible

### ISSUE THREAD

**Issue by Finelarme9** [kreezxil/Localized-Chat#4]
Hello there

I really like your mod idea. Thank you for this. However I have the same problems than [KorgannUntergraethorn](https://minecraft.curseforge.com/projects/localized-chat?comment=13). Hereafter a list of problems/ideas :

- Range detection works only with enableChannels=false prohibiting the use of the command /shout.

- Is there a way to add config for the prefix [From x.x blocks away] ? Also, even more clean is it possible to add a config for a prefix of "messages in range". For example a message in range will appear in chat with the prefix [Nearby message].

- Is there a way to add a special command to toggle (on/off) the permanent/transparent use of "/shout". For example a player write "/shout toggle on" and everyone will see his future message (if he writes again "/shout toggle off" only player in range will see his future message).

Thank you in advance for your work & time.

Ben

NB: I have made my tests on a clean Forge version (1.12/2830) and with your mod only.

**Comment by kreezxil** [comment]
i have stripped the mod down to its core functionality and will have a release for you to test further shortly.

**Comment by kreezxil** [comment]
These are the changes of 3.0.0 which has just been released:

stripped it down to the core parts.
Made sure it handles ranges correctly.
cleaned up the config.
like an American Idol song I fully made this my own mod this time.
Added alternative prefixing to be used in place of displaying numbers.
added compatibility with fakeName mod.
added compatibility with any mod that modifies the name of the player using the customNameTag NBT compound.

Let's test this thoroughly before adding other features.

**Comment by Finelarme9** [comment]
Hi there. I was busy with my job. Thank you for your work. I'm gonna take a look and will give you a complete feedback.
